# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vega < Formula
  desc "AI Agent Orchestration CLI"
  homepage "https://v3ga.dev"
  version "0.8.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/everydev1618/vega-releases/releases/download/v0.8.5/vega_0.8.5_darwin_amd64.tar.gz"
      sha256 "112ab91cff61947433961030aa9ca14d914ff959e63f9046d6d4cbb43ec0ee42"

      define_method(:install) do
        bin.install "vega"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/everydev1618/vega-releases/releases/download/v0.8.5/vega_0.8.5_darwin_arm64.tar.gz"
      sha256 "9bf2198887e8cb1b5d0b8395478004691570be9eab5debe4fca05c9a8a3582f5"

      define_method(:install) do
        bin.install "vega"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/everydev1618/vega-releases/releases/download/v0.8.5/vega_0.8.5_linux_amd64.tar.gz"
      sha256 "3118d6c09029a666847faa80d631790a0ef24e36acf27f979b89f06c0d3e032d"
      define_method(:install) do
        bin.install "vega"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/everydev1618/vega-releases/releases/download/v0.8.5/vega_0.8.5_linux_arm64.tar.gz"
      sha256 "c0addca6f7797bd9ec2d3a08004d163943b102857f4bdfef6991453b3f2b6017"
      define_method(:install) do
        bin.install "vega"
      end
    end
  end

  test do
    system "#{bin}/vega", "version"
  end
end
